-- MySQL Script generated by MySQL Workbench
-- Thu Nov 11 14:22:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Carsharing
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Carsharing` ;

-- -----------------------------------------------------
-- Schema Carsharing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Carsharing` DEFAULT CHARACTER SET utf8 ;
USE `Carsharing` ;

-- -----------------------------------------------------
-- Table `Carsharing`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carsharing`.`Cars` (
  `CarID` INT NOT NULL AUTO_INCREMENT,
  `Manufacturer` VARCHAR(100) NOT NULL,
  `Model` VARCHAR(100) NOT NULL,
  `CostPerHour` DOUBLE UNSIGNED NOT NULL,
  `CostPerDay` DOUBLE UNSIGNED NOT NULL,
  `Status` VARCHAR(20) NOT NULL,
  `ProductionYear` DATE NULL,
  `Description` TEXT(200) NULL,
  `PhotosDirectoryLink` VARCHAR(150) NULL,
  PRIMARY KEY (`CarID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carsharing`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carsharing`.`Clients` (
  `ClientID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `PhoneNumber` INT UNSIGNED NOT NULL,
  `Country` VARCHAR(30) NULL,
  `Sity` VARCHAR(45) NULL,
  PRIMARY KEY (`ClientID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carsharing`.`Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carsharing`.`Payments` (
  `PaymentsID` INT NOT NULL AUTO_INCREMENT,
  `PaymentTime` DATETIME NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Sum` DOUBLE NOT NULL,
  PRIMARY KEY (`PaymentsID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carsharing`.`Employers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carsharing`.`Employers` (
  `EmployersID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `SecondName` VARCHAR(45) NOT NULL,
  `Patronymic` VARCHAR(45) NOT NULL,
  `Salary` DOUBLE UNSIGNED NOT NULL,
  `PhoneNumber` INT UNSIGNED NULL,
  PRIMARY KEY (`EmployersID`, `Salary`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carsharing`.`Contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carsharing`.`Contracts` (
  `Cars_CarID` INT NOT NULL,
  `Clients_ClientID` INT NOT NULL,
  `BeginTime` DATETIME NOT NULL,
  `EndTime` VARCHAR(45) NOT NULL,
  `Payments_PaymentsID` INT NOT NULL,
  `Employers_EmployersID` INT NOT NULL,
  PRIMARY KEY (`Cars_CarID`, `Clients_ClientID`, `BeginTime`, `Payments_PaymentsID`),
  INDEX `fk_Cars_has_Clients_Clients1_idx` (`Clients_ClientID` ASC) VISIBLE,
  INDEX `fk_Cars_has_Clients_Cars_idx` (`Cars_CarID` ASC) VISIBLE,
  INDEX `fk_Treaties_Payments1_idx` (`Payments_PaymentsID` ASC) VISIBLE,
  INDEX `fk_Treaties_Employers1_idx` (`Employers_EmployersID` ASC) VISIBLE,
  CONSTRAINT `fk_Cars_has_Clients_Cars`
    FOREIGN KEY (`Cars_CarID`)
    REFERENCES `Carsharing`.`Cars` (`CarID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_has_Clients_Clients1`
    FOREIGN KEY (`Clients_ClientID`)
    REFERENCES `Carsharing`.`Clients` (`ClientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Treaties_Payments1`
    FOREIGN KEY (`Payments_PaymentsID`)
    REFERENCES `Carsharing`.`Payments` (`PaymentsID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Treaties_Employers1`
    FOREIGN KEY (`Employers_EmployersID`)
    REFERENCES `Carsharing`.`Employers` (`EmployersID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
